
# name: deployment-workflow
# on: push
# jobs:
#     runs-on: ubuntu-latest
#     steps:
#         - name: Get code
#           uses: actions/checkout@v4
#         - name: install node
#           uses: actions/setup-node@
#           with:
#            node-version: 16
#         - name: run 
#           run: npm ci
#         - name: run lint
#           run: npm test
#         - name: run test
#           run: npm test  
#         - name: Build npm
#           run: npm build
#           run: echo "Executing npm"


name: deployment-workflow
on: push
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm lint

      - name: Run tests
        run: npm test  

      - name: Build npm
        run: npm run build

      - name: Echo statement
        run: echo "Executing npm"
